# Generated by Django 6.0.2 on 2026-02-11 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('event_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'events',
            },
        ),
        migrations.CreateModel(
            name='Plage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('slot_duration_minutes', models.PositiveSmallIntegerField()),
                ('break_start_time', models.TimeField(blank=True, null=True)),
                ('break_end_time', models.TimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plages', to='api.event')),
            ],
            options={
                'db_table': 'plages',
            },
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('client_fname', models.CharField(blank=True, max_length=120, null=True)),
                ('client_lname', models.CharField(blank=True, max_length=120, null=True)),
                ('client_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('client_phone', models.CharField(blank=True, max_length=25, null=True)),
                ('item', models.CharField(blank=True, max_length=100, null=True)),
                ('item_description', models.TextField(blank=True, null=True)),
                ('liability_accepted', models.BooleanField(default=False)),
                ('is_canceled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='api.plage')),
            ],
            options={
                'db_table': 'slots',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
                'constraints': [models.UniqueConstraint(condition=models.Q(('email__isnull', False), models.Q(('email', ''), _negated=True)), fields=('email',), name='uq_user_email_not_blank')],
            },
        ),
        migrations.AddIndex(
            model_name='plage',
            index=models.Index(fields=['event', 'name'], name='plages_event_i_ebcfa8_idx'),
        ),
        migrations.AddConstraint(
            model_name='plage',
            constraint=models.UniqueConstraint(condition=models.Q(('name__isnull', False), models.Q(('name', ''), _negated=True)), fields=('event', 'name'), name='uq_plage_event_name_not_null'),
        ),
        migrations.AddIndex(
            model_name='slot',
            index=models.Index(fields=['plage', 'start_at'], name='slots_plage_i_e588b1_idx'),
        ),
        migrations.AddConstraint(
            model_name='slot',
            constraint=models.UniqueConstraint(fields=('plage', 'start_at'), name='uq_slot_plage_startat'),
        ),
    ]
