name: Playwright Tests
## Voir si le déclenchement est approprié pour nos besoins,
## les tests se lancent sur toutes les branches à chaque push et pull requests
## deploie le rapport sur GitHub Pages

permissions:
  contents: write
  pages: write
  id-token: write

on:
  pull_request:
    paths:
      - "FabLab/**"
      - "Playwright/**"
  workflow_dispatch:
  
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Configure Frontend Environment
        run: |
          echo "Configuring Frontend..."
          cat > .env << EOF
          PUBLIC_BASE_URL=${{ secrets.PUBLIC_BASE_URL }}
          EOF
        working-directory: FabLab

      - name: Install front-end dependencies
        run: npm i
        working-directory: FabLab

      - name: Install playwright test dependencies
        run: npm ci
        working-directory: Playwright

      - name: Install Playwright Browsers
        run: npx playwright install chromium
        working-directory: Playwright

      - name: Run Playwright tests
        run: npx playwright test
        working-directory: Playwright

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: ./Playwright/playwright-report/
          retention-days: 1

      